#!/bin/bash
cd '/home/tmarc/sistema.tmarc.pe'
export PATH='/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PORT='3000'
export APP_URL='https://sistema.tmarc.pe'
export DB_HOST='localhost'
export DB_NAME='tmarc_sistema'
export DB_PORT='3307'
export DB_USER='tmarc_usr89'
export BASE_URL='https://sistema.tmarc.pe'
export SMTP_HOST='smtp-relay.gmail.com'
export SMTP_PORT='465'
export SMTP_USER='sistema@tmarc.pe'
export ADMIN_USER='admin'
export EMAIL_FROM='sistema@tmarc.pe'
export JWT_SECRET='26189e2a1825f95fe266a5be3a4881669b88974e4073fa8c74699bac8e718faf51868f91dadc0a0f77b90b6c3faf37b1c3a317fa82981a55d9cfda59bb2e4857'
export ADMIN_EMAIL='sistema@tmarc.pe'
export DB_PASSWORD='Devloper2.'
export SMTP_PASSWORD='sistema@tmarc.pe2026'
export SMTP_USE_AUTH='false'
export ADMIN_PASSWORD='admin123'
export SMTP_FROM_NAME='Sistema Mesa de Partes Virtual'
export SMTP_FROM_EMAIL='sistema@tmarc.pe'
export SMTP_SSL_ENABLED='true'
export HOST='0.0.0.0'
export NODE_ENV='production'
exec node .odin-server.js
