providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "20"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20", "curl", "wget", "git"]

[phases.install]
cmds = ["npm install --production"]

[start]
cmd = "node server.js"
